### ISSUE TITLE
Error "(" unexpected (expecting "then")

### ISSUE THREAD

**Issue by DanTheMan-NL** [mrwhale/limitlessled-bash#5]
Whenever I want to execute this script I get:

led.sh: 57: led.sh: Syntax error: "(" unexpected (expecting "then")

**Comment by mrwhale** [comment]
What shell are you using?

I've just copied and pasted the script and it worked great in

    $ bash --version
    GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

It does not work running directly with fish, zsh, or sh without modifications it seems
